name: Release

on:
  push:
    tags:
      - "v*"
    branches:
      - main

jobs:
  release:
    name: Build and Release Windows Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build Windows Binary
        run: |
          mkdir -p build
          GOOS=windows GOARCH=amd64 go build -o build/quickssh.exe

      - name: Zip Binary
        run: |
          cd build
          zip quickssh-windows-amd64.zip quickssh.exe

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/quickssh-windows-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
