name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build and Release Windows Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install Goreleaser
        run: go install github.com/goreleaser/goreleaser/v2@latest

      - name: Run Goreleaser
        run: goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
